services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    GenSys\GenerateBundle\Maker\:
        resource: '../../Maker/*'
        tags:
            - { name: 'maker.command' }

    GenSys\GenerateBundle\:
        resource: '../../*'
        exclude: '../../{Model,Resources}'
